In [39]:
import pandas as pd

data = pd.read_csv('cancer_reg.csv')
data.head()

,avganncount,avgdeathsperyear,target_deathrate,incidencerate,medincome,popest2015,povertypercent,studypercap,binnedinc,medianage,...,pctprivatecoveragealone,pctempprivcoverage,pctpubliccoverage,pctpubliccoveragealone,pctwhite,pctblack,pctasian,pctotherrace,pctmarriedhouseholds,birthrate
0,1397.0,469,164.9,489.8,61898,260131,11.2,499.748204,"(61494.5, 125635]",39.3,...,NaN,41.6,32.9,14.0,81.780529,2.594728,4.821857,1.843479,52.856076,6.118831
1,173.0,70,161.3,411.6,48127,43269,18.6,23.111234,"(48021.6, 51046.4]",33.0,...,53.8,43.6,31.1,15.3,89.228509,0.969102,2.246233,3.741352,45.372500,4.333096
2,102.0,50,174.7,349.7,49348,21026,14.6,47.560164,"(48021.6, 51046.4]",45.0,...,43.5,34.9,42.1,21.1,90.922190,0.739673,0.465898,2.747358,54.444868,3.729488
3,427.0,202,194.8,430.4,44243,75882,17.1,342.637253,"(42724.4, 45201]",42.8,...,40.3,35.0,45.3,25.0,91.744686,0.782626,1.161359,1.362643,51.021514,4.603841
4,57.0,26,144.4,350.1,49955,10321,12.5,0.000000,"(48021.6, 51046.4]",48.3,...,43.9,35.1,44.0,22.7,94.104024,0.270192,0.665830,0.492135,54.027460,6.796657

In [40]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3047 entries, 0 to 3046
Data columns (total 33 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   avganncount              3047 non-null   float64
 1   avgdeathsperyear         3047 non-null   int64
 2   target_deathrate         3047 non-null   float64
 3   incidencerate            3047 non-null   float64
 4   medincome                3047 non-null   int64
 5   popest2015               3047 non-null   int64
 6   povertypercent           3047 non-null   float64
 7   studypercap              3047 non-null   float64
 8   binnedinc                3047 non-null   object
 9   medianage                3047 non-null   float64
 10  medianagemale            3047 non-null   float64
 11  medianagefemale          3047 non-null   float64
 12  geography                3047 non-null   object
 13  percentmarried           3047 non-null   float64
 14  pctnohs18_24             3047 non-null   float64
 15  pcths18_24               3047 non-null   float64
 16  pctsomecol18_24          762 non-null    float64
 17  pctbachdeg18_24          3047 non-null   float64
 18  pcths25_over             3047 non-null   float64
 19  pctbachdeg25_over        3047 non-null   float64
 20  pctemployed16_over       2895 non-null   float64
 21  pctunemployed16_over     3047 non-null   float64
 22  pctprivatecoverage       3047 non-null   float64
 23  pctprivatecoveragealone  2438 non-null   float64
 24  pctempprivcoverage       3047 non-null   float64
 25  pctpubliccoverage        3047 non-null   float64
 26  pctpubliccoveragealone   3047 non-null   float64
 27  pctwhite                 3047 non-null   float64
 28  pctblack                 3047 non-null   float64
 29  pctasian                 3047 non-null   float64
 30  pctotherrace             3047 non-null   float64
 31  pctmarriedhouseholds     3047 non-null   float64
 32  birthrate                3047 non-null   float64
dtypes: float64(28), int64(3), object(2)
memory usage: 785.7+ KB

In [41]:
data.describe()

,avganncount,avgdeathsperyear,target_deathrate,incidencerate,medincome,popest2015,povertypercent,studypercap,medianage,medianagemale,...,pctprivatecoveragealone,pctempprivcoverage,pctpubliccoverage,pctpubliccoveragealone,pctwhite,pctblack,pctasian,pctotherrace,pctmarriedhouseholds,birthrate
count,3047.000000,3047.000000,3047.000000,3047.000000,3047.000000,3.047000e+03,3047.000000,3047.000000,3047.000000,3047.000000,...,2438.000000,3047.000000,3047.000000,3047.000000,3047.000000,3047.000000,3047.000000,3047.000000,3047.000000,3047.000000
mean,606.338544,185.965868,178.664063,448.268586,47063.281917,1.026374e+05,16.878175,155.399415,45.272333,39.570725,...,48.453774,41.196324,36.252642,19.240072,83.645286,9.107978,1.253965,1.983523,51.243872,5.640306
std,1416.356223,504.134286,27.751511,54.560733,12040.090836,3.290592e+05,6.409087,529.628366,45.304480,5.226017,...,10.083006,9.447687,7.841741,6.113041,16.380025,14.534538,2.610276,3.517710,6.572814,1.985816
min,6.000000,3.000000,59.700000,201.300000,22640.000000,8.270000e+02,3.200000,0.000000,22.300000,22.400000,...,15.700000,13.500000,11.200000,2.600000,10.199155,0.000000,0.000000,0.000000,22.992490,0.000000
25%,76.000000,28.000000,161.200000,420.300000,38882.500000,1.168400e+04,12.150000,0.000000,37.700000,36.350000,...,41.000000,34.500000,30.900000,14.850000,77.296180,0.620675,0.254199,0.295172,47.763063,4.521419
50%,171.000000,61.000000,178.100000,453.549422,45207.000000,2.664300e+04,15.900000,0.000000,41.000000,39.600000,...,48.700000,41.100000,36.300000,18.800000,90.059774,2.247576,0.549812,0.826185,51.669941,5.381478
75%,518.000000,149.000000,195.200000,480.850000,52492.000000,6.867100e+04,20.400000,83.650776,44.000000,42.500000,...,55.600000,47.700000,41.550000,23.100000,95.451693,10.509732,1.221037,2.177960,55.395132,6.493677
max,38150.000000,14010.000000,362.800000,1206.900000,125635.000000,1.017029e+07,47.400000,9762.308998,624.000000,64.700000,...,78.900000,70.700000,65.100000,46.600000,100.000000,85.947799,42.619425,41.930251,78.075397,21.326165

In [42]:
data.isnull().sum()

avganncount                   0
avgdeathsperyear              0
target_deathrate              0
incidencerate                 0
medincome                     0
popest2015                    0
povertypercent                0
studypercap                   0
binnedinc                     0
medianage                     0
medianagemale                 0
medianagefemale               0
geography                     0
percentmarried                0
pctnohs18_24                  0
pcths18_24                    0
pctsomecol18_24            2285
pctbachdeg18_24               0
pcths25_over                  0
pctbachdeg25_over             0
pctemployed16_over          152
pctunemployed16_over          0
pctprivatecoverage            0
pctprivatecoveragealone     609
pctempprivcoverage            0
pctpubliccoverage             0
pctpubliccoveragealone        0
pctwhite                      0
pctblack                      0
pctasian                      0
pctotherrace                  0
pctmarriedhouseholds          0
birthrate                     0
dtype: int64

In [43]:
data = data.dropna(axis=0)
data.isnull().sum()

avganncount                0
avgdeathsperyear           0
target_deathrate           0
incidencerate              0
medincome                  0
popest2015                 0
povertypercent             0
studypercap                0
binnedinc                  0
medianage                  0
medianagemale              0
medianagefemale            0
geography                  0
percentmarried             0
pctnohs18_24               0
pcths18_24                 0
pctsomecol18_24            0
pctbachdeg18_24            0
pcths25_over               0
pctbachdeg25_over          0
pctemployed16_over         0
pctunemployed16_over       0
pctprivatecoverage         0
pctprivatecoveragealone    0
pctempprivcoverage         0
pctpubliccoverage          0
pctpubliccoveragealone     0
pctwhite                   0
pctblack                   0
pctasian                   0
pctotherrace               0
pctmarriedhouseholds       0
birthrate                  0
dtype: int64

In [45]:
data['geography'].unique()

array(['Kittitas County, Washington', 'Lewis County, Washington',
       'Lincoln County, Washington', 'Pacific County, Washington',
       'Spokane County, Washington', 'Thurston County, Washington',
       'Wahkiakum County, Washington', 'Barbour County, West Virginia',
       'Doddridge County, West Virginia', 'Grant County, West Virginia',
       'Greenbrier County, West Virginia',
       'Harrison County, West Virginia', 'Jackson County, West Virginia',
       'Jefferson County, West Virginia', 'Lincoln County, West Virginia',
       'Mineral County, West Virginia',
       'Monongalia County, West Virginia', 'Monroe County, West Virginia',
       'Pocahontas County, West Virginia',
       'Preston County, West Virginia', 'Putnam County, West Virginia',
       'Webster County, West Virginia', 'Chippewa County, Wisconsin',
       'Douglas County, Wisconsin', 'Grant County, Wisconsin',
       'Sherman County, Nebraska', 'York County, Nebraska',
       'Elko County, Nevada', 'Esmeralda County, Nevada',
       'Eureka County, Nevada', 'Lincoln County, Nevada',
       'Mineral County, Nevada', 'Carroll County, New Hampshire',
       'Cheshire County, New Hampshire',
       'Hillsborough County, New Hampshire',
       'Merrimack County, New Hampshire', 'Atlantic County, New Jersey',
       'Bergen County, New Jersey', 'Burlington County, New Jersey',
       'Cape May County, New Jersey', 'Gloucester County, New Jersey',
       'Mercer County, New Jersey', 'Middlesex County, New Jersey',
       'Monmouth County, New Jersey', 'Warren County, New Jersey',
       'Bernalillo County, New Mexico', 'Eddy County, New Mexico',
       'Hidalgo County, New Mexico', 'Taos County, New Mexico',
       'Albany County, New York', 'Cayuga County, New York',
       'Chenango County, New York', 'Louisa County, Virginia',
       'Montgomery County, Virginia', 'Nelson County, Virginia',
       'New Kent County, Virginia', 'Northampton County, Virginia',
       'Orange County, Virginia', 'Rockbridge County, Virginia',
       'Spotsylvania County, Virginia', 'Tazewell County, Virginia',
       'Warren County, Virginia', 'Wise County, Virginia',
       'Colonial Heights city, Virginia', 'Hopewell city, Virginia',
       'Salem city, Virginia', 'Suffolk city, Virginia',
       'Williamsburg city, Virginia', 'Asotin County, Washington',
       'Columbia County, Washington', 'Douglas County, Washington',
       'Chippewa County, Michigan', 'Clinton County, Michigan',
       'Isabella County, Michigan', 'Keweenaw County, Michigan',
       'Midland County, Michigan', 'Ogemaw County, Michigan',
       'Otsego County, Michigan', 'Washtenaw County, Michigan',
       'Cortland County, New York', 'Essex County, New York',
       'Genesee County, New York', 'Macon County, North Carolina',
       'Mecklenburg County, North Carolina',
       'Northampton County, North Carolina',
       'Orange County, North Carolina', 'Person County, North Carolina',
       'Polk County, North Carolina', 'Rowan County, North Carolina',
       'Scotland County, North Carolina',
       'Tyrrell County, North Carolina', 'Vance County, North Carolina',
       'Wilson County, North Carolina', 'Yadkin County, North Carolina',
       'Benson County, North Dakota', 'Eddy County, North Dakota',
       'Grant County, North Dakota', 'Hettinger County, North Dakota',
       'Logan County, North Dakota', 'McLean County, North Dakota',
       'Morton County, North Dakota', 'Ransom County, North Dakota',
       'Stutsman County, North Dakota', 'Arkansas County, Arkansas',
       'Crawford County, Arkansas', 'Cross County, Arkansas',
       'Desha County, Arkansas', 'Drew County, Arkansas',
       'Fulton County, Arkansas', 'Garland County, Arkansas',
       'Johnson County, Arkansas', 'Little River County, Arkansas',
       'Miller County, Arkansas', 'Monroe County, Arkansas',
       'Polk County, Arkansas', 'Prairie County, Arkansas',
       'Randolph County, Arkansas', 'St. Francis County, Arkansas',
       'Saline County, Arkansas', 'Sevier County, Arkansas',
       'Van Buren County, Arkansas', 'Lake County, Montana',
       'Lewis and Clark County, Montana', 'Musselshell County, Montana',
       'Roosevelt County, Montana', 'Wibaux County, Montana',
       'Yellowstone County, Montana', 'Douglas County, Nebraska',
       'Dundy County, Nebraska', 'Garden County, Nebraska',
       'Garfield County, Nebraska', 'Hall County, Nebraska',
       'Howard County, Nebraska', 'Kearney County, Nebraska',
       'Rock County, Nebraska', 'Saunders County, Nebraska',
       'Fayette County, Tennessee', 'Gibson County, Tennessee',
       'Greene County, Tennessee', 'Hamilton County, Tennessee',
       'Hardin County, Tennessee', 'Henry County, Tennessee',
       'Humphreys County, Tennessee', 'Lewis County, Tennessee',
       'Lincoln County, Tennessee', 'Monroe County, Tennessee',
       'Obion County, Tennessee', 'Robertson County, Tennessee',
       'Sequatchie County, Tennessee', 'Stewart County, Tennessee',
       'Andrews County, Texas', 'Atascosa County, Texas',
       'Bailey County, Texas', 'Bell County, Texas',
       'Blanco County, Texas', 'Brazos County, Texas',
       'Brooks County, Texas', 'Brown County, Texas',
       'Catahoula Parish, Louisiana', 'Claiborne Parish, Louisiana',
       'East Feliciana Parish, Louisiana', 'Evangeline Parish, Louisiana',
       'Jefferson Davis Parish, Louisiana', 'Lafourche Parish, Louisiana',
       'Lincoln Parish, Louisiana', 'Ouachita Parish, Louisiana',
       'St. Landry Parish, Louisiana', 'Winn Parish, Louisiana',
       'Aroostook County, Maine', 'York County, Maine',
       'Anne Arundel County, Maryland', 'Caroline County, Maryland',
       'Dorchester County, Maryland', 'Harford County, Maryland',
       'Kent County, Maryland', 'Montgomery County, Maryland',
       "Queen Anne's County, Maryland", "St. Mary's County, Maryland",
       'Talbot County, Maryland', 'Baltimore city, Maryland',
       'Emery County, Utah', 'Kane County, Utah',
       'Washington County, Vermont', 'Appomattox County, Virginia',
       'Caroline County, Virginia', 'Carroll County, Virginia',
       'Culpeper County, Virginia', 'Los Angeles County, California',
       'Merced County, California', 'Plumas County, California',
       'San Bernardino County, California', 'Cullman County, Alabama',
       'San Luis Obispo County, California',
       'Stanislaus County, California', 'Dallas County, Alabama',
       'Boulder County, Colorado', 'Chaffee County, Colorado',
       'Crowley County, Colorado', 'Custer County, Colorado',
       'Denver County, Colorado', 'Elmore County, Alabama',
       'Gilpin County, Colorado', 'Kiowa County, Colorado',
       'Mesa County, Colorado', 'Montrose County, Colorado',
       'Otero County, Colorado', 'Phillips County, Colorado',
       'Franklin County, Massachusetts', 'Allegan County, Michigan',
       'Antrim County, Michigan', 'Bay County, Michigan',
       'Jefferson County, Wisconsin', 'Juneau County, Wisconsin',
       'Langlade County, Wisconsin', 'Menominee County, Wisconsin',
       'Oconto County, Wisconsin', 'Portage County, Wisconsin',
       'Richland County, Wisconsin', 'Taylor County, Wisconsin',
       'Washington County, Wisconsin', 'Waupaca County, Wisconsin',
       'Winnebago County, Wisconsin', 'Hot Springs County, Wyoming',
       'Park County, Wyoming', 'Sheridan County, Wyoming',
       'Jefferson Davis County, Mississippi',
       'Lawrence County, Mississippi', 'Monroe County, Mississippi',
       'Montgomery County, Mississippi', 'Noxubee County, Mississippi',
       'Scott County, Mississippi', 'Webster County, Mississippi',
       'Barton County, Missouri', 'Camden County, Missouri',
       'Dallas County, Missouri', 'Franklin County, Missouri',
       'Jewell County, Kansas', 'Logan County, Kansas',
       'Marion County, Kansas', 'Marshall County, Kansas',
       'Morton County, Kansas', 'Norton County, Kansas',
       'Pawnee County, Kansas', 'Phillips County, Kansas',
       'Republic County, Kansas', 'Rush County, Kansas',
       'Russell County, Kansas', 'Scott County, Kansas',
       'Wabaunsee County, Kansas', 'Woodson County, Kansas',
       'Adair County, Kentucky', 'Anderson County, Kentucky',
       'Bell County, Kentucky', 'Bourbon County, Kentucky',
       'Campbell County, Kentucky', 'Carter County, Kentucky',
       'Casey County, Kentucky', 'Christian County, Kentucky',
       'Fayette County, Alabama', 'Weld County, Colorado',
       'New Haven County, Connecticut', 'Kent County, Delaware',
       'Sussex County, Delaware', 'Broward County, Florida',
       'Calhoun County, Florida', 'Charlotte County, Florida',
       'Gilchrist County, Florida', 'Hamilton County, Florida',
       'Indian River County, Florida', 'Miami-Dade County, Florida',
       'Okeechobee County, Florida', 'St. Johns County, Florida',
       'Seminole County, Florida', 'Taylor County, Florida',
       'Canadian County, Oklahoma', 'Carter County, Oklahoma',
       'Cleveland County, Oklahoma', 'Garvin County, Oklahoma',
       'Greer County, Oklahoma', 'Kay County, Oklahoma',
       'Love County, Oklahoma', 'Payne County, Oklahoma',
       'Pontotoc County, Oklahoma', 'Roger Mills County, Oklahoma',
       'Rogers County, Oklahoma', 'Tillman County, Oklahoma',
       'Tulsa County, Oklahoma', 'Hood River County, Oregon',
       'Klamath County, Oregon', 'Marion County, Oregon',
       'Polk County, Oregon', 'Adams County, Ohio',
       'Ashtabula County, Ohio', 'Clark County, Ohio',
       'Coshocton County, Ohio', 'Cuyahoga County, Ohio',
       'Hardin County, Ohio', 'Mahoning County, Ohio',
       'Morrow County, Ohio', 'Paulding County, Ohio',
       'Perry County, Ohio', 'Preble County, Ohio', 'Putnam County, Ohio',
       'Trumbull County, Ohio', 'Van Wert County, Ohio',
       'Alfalfa County, Oklahoma', 'Atoka County, Oklahoma',
       'Wallowa County, Oregon', 'Wasco County, Oregon',
       'Bedford County, Pennsylvania', 'Berks County, Pennsylvania',
       'Centre County, Pennsylvania', 'Clinton County, Pennsylvania',
       'Erie County, Pennsylvania', 'Franklin County, Pennsylvania',
       'Greene County, Pennsylvania', 'Huntingdon County, Pennsylvania',
       'Indiana County, Pennsylvania', 'Jefferson County, Pennsylvania',
       'Lancaster County, Pennsylvania', 'Lycoming County, Pennsylvania',
       'Pike County, Pennsylvania', 'Potter County, Pennsylvania',
       'Snyder County, Pennsylvania', 'Somerset County, Pennsylvania',
       'Sullivan County, Pennsylvania', 'Washington County, Pennsylvania',
       'Darlington County, South Carolina', 'Calhoun County, Texas',
       'Castro County, Texas', 'Cherokee County, Texas',
       'Comal County, Texas', 'Comanche County, Texas',
       'Cooke County, Texas', 'Crane County, Texas',
       'Crosby County, Texas', 'Falls County, Texas',
       'Floyd County, Texas', 'Franklin County, Texas',
       'Galveston County, Texas', 'Gregg County, Texas',
       'Grimes County, Texas', 'Harris County, Texas',
       'Hays County, Texas', 'Hutchinson County, Texas',
       'Jefferson County, Texas', 'Lavaca County, Texas',
       'Leon County, Texas', 'Lipscomb County, Texas',
       'Mason County, Texas', 'Medina County, Texas',
       'Menard County, Texas', 'Milam County, Texas',
       'Navarro County, Texas', 'Nolan County, Texas',
       'Oldham County, Texas', 'Polk County, Texas',
       'Runnels County, Texas', 'Rusk County, Texas',
       'San Jacinto County, Texas', 'Shelby County, Texas',
       'Somervell County, Texas', 'Gasconade County, Missouri',
       'Greene County, Missouri', 'Grundy County, Missouri',
       'Holt County, Missouri', 'Howard County, Missouri',
       'Howell County, Missouri', 'Jackson County, Missouri',
       'Maries County, Missouri', 'Marion County, Missouri',
       'Morgan County, Missouri', 'Ozark County, Missouri',
       'Perry County, Missouri', 'Pulaski County, Missouri',
       'Ralls County, Missouri', 'Ray County, Missouri',
       'Saline County, Missouri', 'Vernon County, Missouri',
       'Seneca County, New York', 'Suffolk County, New York',
       'Washington County, New York', 'Wayne County, New York',
       'Beaufort County, North Carolina',
       'Chatham County, North Carolina', 'Craven County, North Carolina',
       'Duplin County, North Carolina', 'Hoke County, North Carolina',
       'Clinton County, Kentucky', 'Fayette County, Kentucky',
       'Hancock County, Kentucky', 'Harrison County, Kentucky',
       'Hart County, Kentucky', 'Henry County, Kentucky',
       'Fountain County, Indiana', 'Franklin County, Indiana',
       'Hamilton County, Indiana', 'Howard County, Indiana',
       'Knox County, Indiana', 'Lawrence County, Indiana',
       'Monroe County, Indiana', 'Montgomery County, Indiana',
       'Morgan County, Indiana', 'Parke County, Indiana',
       'Perry County, Indiana', 'Putnam County, Indiana',
       'Switzerland County, Indiana', 'Union County, Indiana',
       'Warren County, Indiana', 'Warrick County, Indiana',
       'Wayne County, Indiana', 'Wells County, Indiana',
       'Allamakee County, Iowa', 'Black Hawk County, Iowa',
       'Clinton County, Iowa', 'Dallas County, Iowa',
       'Tattnall County, Georgia', 'Tift County, Georgia',
       'Walton County, Georgia', 'Washington County, Georgia',
       'Wheeler County, Georgia', 'Bingham County, Idaho',
       'Blaine County, Idaho', 'Bonneville County, Idaho',
       'Butte County, Idaho', 'Custer County, Idaho',
       'Jefferson County, Idaho', 'Lemhi County, Idaho',
       'Madison County, Idaho', 'Twin Falls County, Idaho',
       'Valley County, Idaho', 'Bureau County, Illinois',
       'Clay County, Illinois', 'Crawford County, Illinois',
       'Cumberland County, Illinois', 'Forsyth County, Georgia',
       'Gilmer County, Georgia', 'Gordon County, Georgia',
       'Habersham County, Georgia', 'Harris County, Georgia',
       'Heard County, Georgia', 'Jackson County, Georgia',
       'Lowndes County, Georgia', 'Lumpkin County, Georgia',
       'Madison County, Georgia', 'Morgan County, Georgia',
       'Muscogee County, Georgia', 'Randolph County, Georgia',
       'Screven County, Georgia', 'Spalding County, Georgia',
       'Carver County, Minnesota', 'Clearwater County, Minnesota',
       'Freeborn County, Minnesota', 'Grant County, Minnesota',
       'Itasca County, Minnesota', 'Kittson County, Minnesota',
       'Lyon County, Minnesota', 'Mahnomen County, Minnesota',
       'Marshall County, Minnesota', 'Mille Lacs County, Minnesota',
       'Morrison County, Minnesota', 'Nobles County, Minnesota',
       'Norman County, Minnesota', 'Pennington County, Minnesota',
       'Red Lake County, Minnesota', 'Renville County, Minnesota',
       'Roseau County, Minnesota', 'Todd County, Minnesota',
       'Wadena County, Minnesota', 'Waseca County, Minnesota',
       'Adams County, Mississippi', 'Amite County, Mississippi',
       'Benton County, Mississippi', 'Chickasaw County, Mississippi',
       'Choctaw County, Mississippi', 'Claiborne County, Mississippi',
       'Clarke County, Mississippi', 'Coahoma County, Mississippi',
       'Covington County, Mississippi', 'DeSoto County, Mississippi',
       'Knox County, Kentucky', 'Larue County, Kentucky',
       'Laurel County, Kentucky', 'Livingston County, Kentucky',
       'Logan County, Kentucky', 'Marion County, Kentucky',
       'Mercer County, Kentucky', 'Oldham County, Kentucky',
       'Owsley County, Kentucky', 'Pendleton County, Kentucky',
       'Powell County, Kentucky', 'Spencer County, Kentucky',
       'Todd County, Kentucky', 'Union County, Kentucky',
       'Washington County, Kentucky', 'Wayne County, Kentucky',
       'Acadia Parish, Louisiana', 'Beauregard Parish, Louisiana',
       'Columbia County, Georgia', 'Coweta County, Georgia',
       'Crawford County, Georgia', 'Dawson County, Georgia',
       'Echols County, Georgia', 'Effingham County, Georgia',
       'Evans County, Georgia', 'Lamar County, Alabama',
       'Appling County, Georgia', 'Atkinson County, Georgia',
       'Banks County, Georgia', 'Berrien County, Georgia',
       'Bleckley County, Georgia', 'Brantley County, Georgia',
       'Brooks County, Georgia', 'Bryan County, Georgia',
       'Calhoun County, Georgia', 'Madison County, Alabama',
       'Marion County, Alabama', 'Tallapoosa County, Alabama',
       'Haines Borough, Alaska', 'Kenai Peninsula Borough, Alaska',
       'Ketchikan Gateway Borough, Alaska',
       'Yukon-Koyukuk Census Area, Alaska', 'Apache County, Arizona',
       'Graham County, Arizona', 'Cherokee County, Alabama',
       'Greenlee County, Arizona', 'La Paz County, Arizona',
       'Santa Cruz County, Arizona', 'Hampton County, South Carolina',
       'Marion County, South Carolina', 'Newberry County, South Carolina',
       'Pickens County, South Carolina', 'Saluda County, South Carolina',
       'York County, South Carolina', 'Edmunds County, South Dakota',
       'Fall River County, South Dakota', 'Gregory County, South Dakota',
       'Lake County, South Dakota', 'Lyman County, South Dakota',
       'Perkins County, South Dakota', 'Stanley County, South Dakota',
       'Tripp County, South Dakota', 'Benton County, Tennessee',
       'Carroll County, Tennessee', 'Coffee County, Tennessee',
       'Crockett County, Tennessee', 'Effingham County, Illinois',
       'Jefferson County, Illinois', 'Kane County, Illinois',
       'Lake County, Illinois', 'LaSalle County, Illinois',
       'McLean County, Illinois', 'Macoupin County, Illinois',
       'Ogle County, Illinois', 'Pike County, Illinois',
       'Sangamon County, Illinois', 'Will County, Illinois',
       'Winnebago County, Illinois', 'Brown County, Indiana',
       'Clark County, Indiana', 'DeKalb County, Indiana',
       'Elkhart County, Indiana', 'Fayette County, Indiana',
       'Dubuque County, Iowa', 'Emmet County, Iowa',
       'Fayette County, Iowa', 'Franklin County, Iowa',
       'Greene County, Iowa', 'Hancock County, Iowa',
       'Henry County, Iowa', 'Howard County, Iowa', 'Jasper County, Iowa',
       'Louisa County, Iowa', 'Marion County, Iowa',
       'Marshall County, Iowa', 'Sac County, Iowa', 'Scott County, Iowa',
       'Union County, Iowa', 'Washington County, Iowa',
       'Wayne County, Iowa', 'Winnebago County, Iowa',
       'Winneshiek County, Iowa', 'Allen County, Kansas',
       'Anderson County, Kansas', 'Chautauqua County, Kansas',
       'Clay County, Kansas', 'Comanche County, Kansas',
       'Cowley County, Kansas', 'Finney County, Kansas',
       'Ford County, Kansas', 'Geary County, Kansas'], dtype=object)

In [46]:
geo_map = data['geography'].value_counts(normalize=True)
data['geography'] = data['geography'].map(geo_map)

In [47]:
import re

def interval_to_midpoint(interval_str):
    if pd.isna(interval_str):
        return None
    
    numbers = re.findall(r'[\d\.]+', interval_str)
    if len(numbers) >= 2:
        left = float(numbers[0])
        right = float(numbers[1])
        return (left + right) / 2
    return None

data['binnedinc'] = data['binnedinc'].apply(interval_to_midpoint)

In [48]:
data['binnedinc']

1       49534.00
3       43962.70
4       49534.00
7       38888.25
14      49534.00
          ...
3033    46611.30
3034    43962.70
3043    49534.00
3044    52796.00
3046    41543.55
Name: binnedinc, Length: 591, dtype: float64

In [50]:
y = data['target_deathrate']
X = data.drop(columns=['target_deathrate'])

In [51]:
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

scaler = StandardScaler()

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [53]:
from sklearn.neighbors import KNeighborsRegressor
from sklearn.model_selection import GridSearchCV, KFold
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline

param_grid = {
    'n_neighbors': [3, 5, 7, 9, 11, 15, 21, 31],
    'weights': ['uniform', 'distance'],
    'p': [1, 2], 
    'metric': ['minkowski', 'euclidean', 'manhattan'] 
}

knn = KNeighborsRegressor()

grid_search = GridSearchCV(
    knn, 
    param_grid, 
    cv=5,                 
    scoring='neg_mean_squared_error',  
    n_jobs=-1,            
    verbose=1
)

grid_search.fit(X_train, y_train)

print("Лучшие параметры:", grid_search.best_params_)
print("Лучший MSE:", -grid_search.best_score_)

best_knn = grid_search.best_estimator_

test_score = best_knn.score(X_test, y_test)
print("R2 на тесте:", test_score)

Fitting 5 folds for each of 96 candidates, totalling 480 fits
Лучшие параметры: {'metric': 'minkowski', 'n_neighbors': 9, 'p': 2, 'weights': 'distance'}
Лучший MSE: 467.72811912026657
R2 на тесте: 0.17643409884523287

In [ ]:
col = X.columns
df_analysis = pd.DataFrame(X_train, columns=col)  
df_analysis['target_deathrate'] = y_train.values

correlations = df_analysis.corr()['target_deathrate'].sort_values(ascending=False)
print("Корреляция признаков с целевой переменной:")
print(correlations)

# Если корреляции близки к 0 (±0.1) - признаки не информативны

Корреляция признаков с целевой переменной:
target_deathrate           1.000000
pctpubliccoveragealone     0.419726
povertypercent             0.401861
pcths25_over               0.381250
pctpubliccoverage          0.377199
incidencerate              0.371042
pctunemployed16_over       0.364295
pctblack                   0.265681
pcths18_24                 0.260150
pctnohs18_24               0.108359
medianagefemale           -0.002958
medianage                 -0.010881
studypercap               -0.032296
medianagemale             -0.044221
birthrate                 -0.100731
avgdeathsperyear          -0.103379
popest2015                -0.114015
avganncount               -0.142849
pctwhite                  -0.165293
pctsomecol18_24           -0.176761
pctasian                  -0.197027
pctotherrace              -0.211836
pctempprivcoverage        -0.246863
percentmarried            -0.254638
pctmarriedhouseholds      -0.308589
pctbachdeg18_24           -0.316374
pctprivatecoveragealone   -0.344451
pctprivatecoverage        -0.356193
binnedinc                 -0.368029
medincome                 -0.398447
pctemployed16_over        -0.438463
pctbachdeg25_over         -0.443852
geography                       NaN
Name: target_deathrate, dtype: float64

In [58]:
from sklearn.feature_selection import SelectKBest, f_regression

# Выбираем топ-10 признаков по корреляции
selector = SelectKBest(score_func=f_regression, k=10)
X_train_selected = selector.fit_transform(X_train, y_train)
X_test_selected = selector.transform(X_test)

knn_selected = KNeighborsRegressor(
    n_neighbors=9, 
    weights='distance', 
    p=2, 
    metric='minkowski'
)
knn_selected.fit(X_train_selected, y_train)
print(f"R2 на топ-10 признаках: {knn_selected.score(X_test_selected, y_test):.4f}")

selected_indices = selector.get_support(indices=True)
selected_features = [col[i] for i in selected_indices]
print("Выбранные признаки:", selected_features)

R2 на топ-10 признаках: 0.2477
Выбранные признаки: ['incidencerate', 'medincome', 'povertypercent', 'binnedinc', 'pcths25_over', 'pctbachdeg25_over', 'pctemployed16_over', 'pctunemployed16_over', 'pctpubliccoverage', 'pctpubliccoveragealone']

In [59]:
from sklearn.ensemble import RandomForestRegressor

rf = RandomForestRegressor(n_estimators=100, random_state=42)
rf.fit(X_train_selected, y_train)  
print(f"Random Forest R2: {rf.score(X_test_selected, y_test):.4f}")

feature_importance = pd.DataFrame({
    'feature': selected_features,
    'importance': rf.feature_importances_
}).sort_values('importance', ascending=False)
print("\nВажность признаков (Random Forest):")
print(feature_importance)

Random Forest R2: 0.1872

Важность признаков (Random Forest):
                  feature  importance
0           incidencerate    0.251091
5       pctbachdeg25_over    0.170554
6      pctemployed16_over    0.138716
7    pctunemployed16_over    0.086488
9  pctpubliccoveragealone    0.077884
4            pcths25_over    0.077625
1               medincome    0.069462
2          povertypercent    0.060889
8       pctpubliccoverage    0.054898
3               binnedinc    0.012392